# Application
spring.application.name=rate-limiter-service
server.port=8080

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Token Bucket Algorithm
rate.limiter.token.capacity=10
rate.limiter.token.refill-rate=10
rate.limiter.token.refill-duration-seconds=60

# Sliding Window Algorithm
rate.limiter.sliding.limit=10
rate.limiter.sliding.window-seconds=60

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.eswarr.ratelimiter=DEBUG
